var homePage="";
homePage += "<header class=\"bg-dark\">";
homePage += "                <div id=\"carouselSlidesOnly\" class=\"carousel slide\" data-bs-ride=\"carousel\" data-bs-interval=\"2500\">";
homePage += "                    <div class=\"carousel-indicators\">";
homePage += "                        <button type=\"button\" data-bs-target=\"#carouselSlidesOnly\" data-bs-slide-to=\"0\" class=\"active\" aria-current=\"true\" aria-label=\"Slide 1\"><\/button>";
homePage += "                        <button type=\"button\" data-bs-target=\"#carouselSlidesOnly\" data-bs-slide-to=\"1\" aria-label=\"Slide 2\"><\/button>";
homePage += "                        <button type=\"button\" data-bs-target=\"#carouselSlidesOnly\" data-bs-slide-to=\"2\" aria-label=\"Slide 3\"><\/button>";
homePage += "                    <\/div>";
homePage += "                    <div class=\"carousel-inner\">";
homePage += "                        <div class=\"carousel-item active\">";
homePage += "                            <img class=\"d-block w-100\" src=\"assets\/candybannerji\/candy_banner1_fix.png\" alt=\"First slide\">";
homePage += "                        <\/div>";
homePage += "                        <div class=\"carousel-item\">";
homePage += "                            <img class=\"d-block w-100\" src=\"assets\/candybannerji\/candy_banner2_fix.png\" alt=\"Second slide\">";
homePage += "                        <\/div>";
homePage += "                          <div class=\"carousel-item\">";
homePage += "                            <img class=\"d-block w-100\" src=\"assets\/candybannerji\/candy_banner3_fix.png\" alt=\"Third slide\">";
homePage += "                        <\/div>";
homePage += "                    <\/div>";
homePage += "                <\/div>";
homePage += "        <\/header>";
homePage += "        <!-- Section-->";
homePage += "        <section class=\"py-5\">";
homePage += "            <div class=\"container px-4 px-lg-5 mt-5\">";
homePage += "                <div id=\"productSection\" class=\"row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center\">";
homePage += "                <\/div>";
homePage += "            <\/div>";
homePage += "        <\/section>";

var categoryPage="";
categoryPage += "       <div id=\"headerDiv\" class=\"container text-center pt-5 font-kanit\">";
categoryPage += "        <\/div>";
categoryPage += "        <section class=\"py-5\">";
categoryPage += "            <div class=\"container px-4 px-lg-5 mt-5\">";
categoryPage += "                <div id=\"productSection\" class=\"row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center\">";
categoryPage += "                <\/div>";
categoryPage += "            <\/div>";
categoryPage += "        <\/section>";

var aboutPage="";
aboutPage += "        <div id=\"aboutDiv\" class=\"container text-center font-kanit\">";
aboutPage += "";
aboutPage += "            <h2 class=\"py-5\">Nasa zgodba<\/h2>";
aboutPage += "";
aboutPage += "            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus urna mauris, condimentum in lectus in, lobortis suscipit quam. Nullam sapien arcu, sagittis et ipsum ut, fringilla mattis ex. Nulla aliquet quis nisl eu congue. Nam sit amet nunc id neque ullamcorper efficitur non ac ipsum. Suspendisse fringilla nisi felis, vel feugiat metus mollis quis. Donec venenatis fringilla faucibus. Nunc luctus, orci id fringilla vehicula, ipsum leo fermentum elit, in suscipit quam augue ut lacus. Interdum et malesuada fames ac ante ipsum primis in faucibus.";
aboutPage += "";
aboutPage += "Sed lacus enim, pretium vel placerat et, dapibus ut elit. Curabitur feugiat volutpat nulla, a porttitor risus blandit semper. Pellentesque efficitur ultricies facilisis. Nullam finibus nunc ligula, eu convallis mi molestie vitae. Sed sit amet ante sit amet ligula commodo mattis sit amet consequat mi. Nulla dapibus enim neque, eget ornare mauris dapibus at. Vestibulum non diam diam. Duis condimentum iaculis orci, et ornare mi viverra id. Etiam dui mi, lobortis eu lobortis et, sagittis a tortor.";
aboutPage += "";
aboutPage += "Aliquam ut condimentum libero. Etiam consectetur felis quis porta ornare. Nam non nunc suscipit neque vulputate venenatis. Donec a ante in magna tempus consequat. Morbi mauris elit, vestibulum in dignissim nec, placerat vitae lectus. Nunc elementum ligula vitae orci faucibus, vitae ullamcorper felis dapibus. Fusce commodo tincidunt elit, non placerat orci volutpat ac. Aliquam id sem ut arcu ornare laoreet in a lacus. Aliquam in erat a nisi gravida sagittis sit amet vel nunc. Cras convallis semper molestie. Etiam fermentum lectus non quam facilisis, in blandit ante facilisis. Vestibulum sodales nulla in dictum ullamcorper. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Phasellus nec libero mauris.";
aboutPage += "";
aboutPage += "Nulla euismod massa orci. Proin eu dui lorem. Pellentesque vel mauris in nunc sollicitudin ullamcorper. Nulla tempus scelerisque neque non faucibus. Nullam ornare rutrum justo ut ornare. Sed at accumsan nulla, quis vehicula leo. Integer sagittis, risus sit amet sodales sagittis, mauris purus ultricies orci, ut elementum ex est eu orci. Nullam erat metus, aliquam ornare consectetur sit amet, finibus nec metus. Nunc rhoncus neque vel odio auctor, vel vehicula nibh interdum. Sed eu nibh posuere, rhoncus felis in, molestie tortor. Phasellus eu leo nec sapien facilisis condimentum. Phasellus nec blandit odio, vitae lacinia erat. Mauris ultricies venenatis nulla et mollis. Mauris blandit odio efficitur nibh scelerisque tincidunt. Quisque finibus pellentesque erat, in vehicula orci dapibus a. Aliquam lacus libero, efficitur vel hendrerit vel, gravida non lectus.";
aboutPage += "";
aboutPage += "Morbi sed mauris tempus, ultrices justo a, blandit est. Mauris vitae est laoreet, mollis nunc vel, dapibus massa. Aliquam erat volutpat. Donec interdum, neque ut interdum volutpat, nunc leo condimentum tellus, ac fringilla erat tortor in turpis. Pellentesque vehicula facilisis leo, et aliquet orci sollicitudin nec. Suspendisse vehicula rhoncus leo, et iaculis nunc accumsan eget. Donec bibendum semper diam, nec finibus ante maximus sit amet. Cras interdum, tortor quis convallis pulvinar, metus nisl porta quam, sit amet viverra metus tellus ut risus.<\/p>";
aboutPage += "";
aboutPage += "<img class=\"d-block w-50 py-5 mx-auto\" src=\"assets\/team.jpg\">";
aboutPage += "        <\/div>";

var productPage="";
productPage += "            <div class=\"container\">";
productPage += "                <div class=\"row\">";
productPage += "                    <div id=\"imageDiv\" class=\"col card card-product-page\">";
productPage += "                        ";
productPage += "                    <\/div>";
productPage += "                    <div class=\"col\">";
productPage += "                        <div  id=\"descDiv\"class=\"py-5\">";
productPage += "                            <h2 id=\"productname\"><\/h2>";
productPage += "                        <\/div>";
productPage += "                    <\/div>";
productPage += "                <\/div>";
productPage += "            <\/div>";

var cartPage="";
cartPage += "      <div id = \"cartContainer\" class=\"container\">    ";
cartPage += "";
cartPage += "  <\/div>";

